### ISSUE TITLE
Incorrect Mistweaver Monk & Holy Paladin Raid Role

### ISSUE THREAD

**Issue by mdavies123** [ultijlam/grid-layout-by-role#1]
Mistweaver monks and holy paladins are grouped in the healer raid role but it may be more accurate to place them in the melee group.

**Comment by johnnylam88** [comment]
This is best left to a selectable option since people have wanted it both the way it currently is as well as what you have proposed.  The argument for your side of it is for spells like Chain Heal.  The other side would prefer seeing healers as a separate group so they can prioritize those members if needed.

The next release of GridLayoutByRole will have an options panel to select how to sort MW monks and Holy Paladins as either melee or healers, as well as to reorder the groups for those that prefer TANKS > HEALERS > MELEE > RANGED as opposed to the current TANKS > MELEE > HEALERS > RANGED.

**Comment by johnnylam88** [comment]
The 8.0.2 release provides options to reorder the groups as well as sort monk and paladin healers into the melee group.
